name: "eInk Art Gallery"
description: "eInk Art Gallery add-on!"
version: "0.0.3"
slug: "eink-art-gallery"
url: "https://github.com/kotope/eink-art-gallery"
startup: application
boot: auto
init: false
arch:
  - aarch64
  - amd64
ports:
  8112/tcp: 8112
ports_description:
  8112/tcp: e-ink gallery Web Interface
webui: "http://[HOST]:[PORT:8112]"
options: {}
schema: {}
map:
  - share:rw # This mounts the host's share folder to /share inside the container

